spring:
  profiles:
    active: dev

  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: HELLO
    password: 1234

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.OracleDialect
    hibernate:
      ddlAuto: create

  # 타임리프 설정 #
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/